# Generated by Django 4.2 on 2023-04-29 07:33

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=962626538, unique=True, validators=[users.validators.PhoneValidator()], verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
