# Generated by Django 4.2 on 2023-05-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.IntegerField(verbose_name='Здание')),
                ('block', models.CharField(blank=True, max_length=5, null=True, verbose_name='Корпус')),
                ('floors', models.IntegerField(blank=True, null=True, verbose_name='Этажей в здании')),
            ],
        ),
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Самара', max_length=25, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='units/', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Published',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=True, verbose_name='Время размещения')),
            ],
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название объекта')),
                ('square', models.FloatField(verbose_name='Площадь, m2')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание объекта')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('flat', models.IntegerField(blank=True, null=True, verbose_name='Номер помещения')),
                ('price', models.FloatField(max_length=2, verbose_name='Цена, тыс. руб')),
                ('deal', models.CharField(choices=[('Продажа', 'Продажа'), ('Аренда', 'Аренда')], default='Продажа', max_length=7, verbose_name='Тип предложения')),
            ],
        ),
    ]
