# Generated by Django 4.2 on 2023-04-29 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.IntegerField(verbose_name='Здание')),
                ('block', models.CharField(blank=True, max_length=5, null=True, verbose_name='Корпус')),
                ('floors', models.IntegerField(blank=True, null=True, verbose_name='Этажей в здании')),
            ],
        ),
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Самара', max_length=25, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('flat', models.IntegerField(blank=True, null=True, verbose_name='Квартира')),
            ],
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название объекта')),
                ('square', models.FloatField(verbose_name='Площадь')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='units/', verbose_name='Фотография')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='units.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='units.buildings')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='units.citys')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='units.flats')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.streets')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='units.unit')),
            ],
        ),
    ]
