# Generated by Django 4.2 on 2023-05-17 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL, verbose_name='Автор интервью'),
        ),
        migrations.AddField(
            model_name='unit',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='units.buildings'),
        ),
        migrations.AddField(
            model_name='unit',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='units.citys'),
        ),
        migrations.AddField(
            model_name='unit',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='units.streets'),
        ),
        migrations.AddField(
            model_name='published',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published', to='units.unit'),
        ),
        migrations.AddField(
            model_name='image',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='units.unit'),
        ),
    ]
