# Generated by Django 4.2 on 2023-05-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='published',
            name='answer',
            field=models.BooleanField(default=True),
        ),
    ]
