# Generated by Django 4.2 on 2023-04-29 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_remove_unit_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='published',
            name='pub_date',
            field=models.DateTimeField(auto_created=True, verbose_name='Время размещения'),
        ),
        migrations.AlterField(
            model_name='published',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published', to='units.unit'),
        ),
    ]
