# Generated by Django 4.2 on 2023-05-23 09:38

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.PositiveBigIntegerField(default=79626265386, validators=[users.validators.PhoneValidator()], verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
