# Generated by Django 4.2 on 2023-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_alter_unit_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='building',
            field=models.IntegerField(verbose_name='Дом.'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этажность здания'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, руб'),
        ),
    ]
