# Generated by Django 4.2 on 2023-05-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_alter_buildings_building_alter_buildings_floors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='price',
            field=models.FloatField(max_length=2, verbose_name='Цена, руб'),
        ),
    ]
