# Generated by Django 4.2 on 2023-06-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_alter_unit_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-pk']},
        ),
    ]
