# Generated by Django 4.2 on 2023-06-05 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_delete_message_alter_unit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=True, verbose_name='Время размещения')),
                ('answer', models.BooleanField(default=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special', to='units.unit')),
            ],
            options={
                'verbose_name': 'Специальное предложение',
                'ordering': ['-pub_date'],
            },
        ),
    ]
