# Generated by Django 4.2 on 2023-06-04 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0009_delete_message_alter_unit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ip', to=settings.AUTH_USER_MODEL)),
                ('visits', models.ManyToManyField(blank=True, related_name='user_visits', to='service.ip')),
            ],
        ),
        migrations.CreateModel(
            name='UnitVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='units.unit')),
                ('views', models.ManyToManyField(blank=True, related_name='unit_views', to='service.ip')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now_add=True, verbose_name='Дата')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.PositiveBigIntegerField(validators=[users.validators.PhoneValidator()], verbose_name='Phone')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='service.ip')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
