# Generated by Django 4.2 on 2023-07-07 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='UserIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ip', to=settings.AUTH_USER_MODEL)),
                ('visits', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_visits', to='service.ip')),
            ],
        ),
        migrations.CreateModel(
            name='UnitVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Date&Time')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='units.unit')),
                ('views', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='unit_views', to='service.ip')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата добавления')),
                ('mark', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('author', models.CharField(blank=True, default='Гость', max_length=20, verbose_name='Имя')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ip')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now_add=True, verbose_name='Дата')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.PositiveBigIntegerField(validators=[users.validators.PhoneValidator()], verbose_name='Phone')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='service.ip')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
