# Generated by Django 4.2 on 2023-06-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitvisits',
            name='views',
        ),
        migrations.RemoveField(
            model_name='userip',
            name='visits',
        ),
        migrations.AddField(
            model_name='unitvisits',
            name='views',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='unit_views', to='service.ip'),
        ),
        migrations.AddField(
            model_name='userip',
            name='visits',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_visits', to='service.ip'),
        ),
    ]
