# Generated by Django 4.2 on 2023-06-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_unitvisits_views_remove_userip_visits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата добавления')),
                ('mark', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('author', models.CharField(default='Гость', max_length=20, verbose_name='Имя')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ip')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
