# Generated by Django 4.2 on 2023-06-07 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_special'),
        ('service', '0002_remove_unitvisits_views_remove_userip_visits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitLocation',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='units.unit')),
                ('longitude', models.CharField(max_length=10, verbose_name='Долгота')),
                ('latitude', models.CharField(max_length=10, verbose_name='Широта')),
            ],
            bases=('units.unit',),
        ),
    ]
