# Generated by Django 4.2 on 2023-06-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='Гость', max_length=20, verbose_name='Имя'),
        ),
    ]
