# Generated by Django 4.2 on 2023-06-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='unitvisits',
            name='dt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default='2023-06-01 00:00', verbose_name='Date&Time'),
            preserve_default=False,
        ),
    ]
